server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: ${WIS2_GDC_API_URL}
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
      url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
      attribution: 'Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /tmp/wis2-gdc-process-manager.db
        output_dir: /tmp/

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: WMO WIS2 Global Discovery Catalogue instance
        description: WMO WIS2 Global Discovery Catalogue instance
        keywords:
            - wmo
            - wis2
            - gdc
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0
        url: https://github.com/wmo-im/wis2-gdc
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0
    provider:
        name: GDC provider name
        url: https://github.com/wmo-im/wis2-gdc
    contact:
        name: Firstname Lastname
        position: Position name
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: pygeoapi@lists.osgeo.org
        url: https://github.com/wmo-im/wis2-gdc
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    wis2-discovery-metadata:
        type: collection
        title: WIS2 discovery metadata
        description: WIS2 discovery metadata
        keywords: [wmo, wis2, gdc]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: WMO Information System (WIS) | World Meteorological Organization
              href: https://community.wmo.int/en/activity-areas/wis
              hreflang: en-CA
            - type: application/zip
              rel: archives
              title: WIS2 discovery metadata archive (generated daily)
              href: ${WIS2_GDC_API_URL}/wis2-discovery-metadata-archive.zip
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: ${WIS2_GDC_BACKEND_TYPE}
              data: ${WIS2_GDC_BACKEND_CONNECTION}
              id_field: id
              time_field: updated

    pywcmp-wis2-wcmp2-ets:
        type: process
        processor:
            name: pywcmp.pygeoapi_plugin.WCMP2ETSProcessor

    pywcmp-wis2-wcmp2-kpi:
        type: process
        processor:
            name: pywcmp.pygeoapi_plugin.WCMP2KPIProcessor
